### ISSUE TITLE
Youtube related

### ISSUE THREAD

**Issue by camcfa** [yoriiis/vlitejs#34]
Hi, thanks for your development.

I saw the Youtube example on your website, and it doesn't show Youtube Related videos and that's what I want.
When I initialize my video, play and pause it, it shows me Related videos on Pause. Is there some option to disable it?

Thank you

**Comment by yoriiis** [comment]
Hi @camcfa, there is no option to disable the related video since august 2018.
More information on the [documentation](https://developers.google.com/youtube/player_parameters#release_notes_08_23_2018).
