### ISSUE TITLE
Retain initial element classes

### ISSUE THREAD

**Issue by dy** [yoriiis/vlitejs#45]
I expected
```js
<div id="player" class="vlite-js player" data-youtube-id="{{ page.video }}"></div>
```
to keep the `.player` class and just insert content.
But it seems to be replaced with new element, anyways class gets lost.

I need to limit video height to `50vh` for wide screens. What's the best way to accomplish that? Wrapping into a container doesn't seem to help.

**Comment by dy** [comment]
Answering my question:
```
.v-vlite.v-video {
    padding-top: min(56.25%, 61.8vh);
}
```

**Comment by dy** [comment]
@yoriiis is it worth retaining initial container element and it's classes?

**Comment by yoriiis** [comment]
@dy The element is automatically replaced with an iframe only when the provider's APIs are used (Youtube and Vimeo), this is normal behavior as specified in the [YouTube documentation](https://developers.google.com/youtube/iframe_api_reference#Getting_Started).
It's quite specific and there are no plans to handle this.

**Comment by dy** [comment]
Right, but I rather meant retaining container classes provided by user

**Comment by yoriiis** [comment]
In fact, the element is not a container, it is a placeholder for the iframe.
You can add the classes on a parent element if necessary, which will not be altered.
This would require managing attributes (classes, identifiers, style, etc.) and rewriting them on the iframe, complicated for a fairly specific need.
