### ISSUE TITLE
Big button is kept on the screen

### ISSUE THREAD

**Issue by dy** [yoriiis/vlitejs#46]
1. Init youtube as so:
![image](https://user-images.githubusercontent.com/300067/122625400-f4fcf600-d072-11eb-8883-149c98379a13.png)
(that mixup of youtube play and vlitejs play is uneasy)

2. Click in the middle of progress bar:
![image](https://user-images.githubusercontent.com/300067/122625418-0a722000-d073-11eb-8e5d-05d30a431c36.png)

The big button is kept on the screen, although the playback has started.

**Comment by dy** [comment]
In general, I'd like to somehow skip youtube poster, for that I'd need to start video, but play seems to be blocked due to #44

**Comment by yoriiis** [comment]
1. Clicking on the progress bar does not trigger playback. If the video was paused, it will remain so until you click the play button.
2. The click on the progress bar do not trigger the playback. If the video was paused it will remain paused until you click on the play button.

**Comment by yoriiis** [comment]
Okay I found the problem. Without the poster, if the user clicks on the progress bar, the seekTo is dispatch without going through the 'play' function.

Fixed in #49.

**Comment by yoriiis** [comment]
This has been fixed and merged in `main`.
Release [`4.0.2`](https://github.com/yoriiis/vlitejs/releases/tag/4.0.2) is available ! 🎉
