### ISSUE TITLE
Make the value of delayAutoHide adjustable

### ISSUE THREAD

**Issue by kbahchevanov** [yoriiis/vlitejs#59]
### Describe the proposed feature.

The value of delayAutoHide (related to the control bar) does not have to hardcoded to 3s, but can be set as an option value.

**Comment by yoriiis** [comment]
Hi @kbahchevanov, thanks for the report.

This has been added and merged in `main`.
Release [`4.0.5`](https://github.com/yoriiis/vlitejs/releases/tag/4.0.5) is available ! 🎉
