### ISSUE TITLE
vlitejs 3.0.2 uninstallable

### ISSUE THREAD

**Issue by charlemagnelasse** [yoriiis/vlitejs#6]
Just wanted to show the problem in https://github.com/yoriiis/chunks-webpack-plugin/issues/9 with the demo/ directory but then hit the problem of https://github.com/yoriiis/chunks-webpack-plugin/issues/6 again (just with vlitejs).

**Comment by yoriiis** [comment]
Hi @charlemagnelasse, thanks for the report.

This has been fixed and merged in `master`.
Release [`3.0.3`](https://github.com/yoriiis/vlitejs/releases/tag/3.0.3) is available ! 🎉
