### ISSUE TITLE
Vimeo provider error

### ISSUE THREAD

**Issue by shamil9** [yoriiis/vlitejs#65]
### Describe the bug

Hello

Thank you for your work. I'm having some problems with vimeo provider.
When calling `player.play()` method I'm getting this error

```
Unknown player. Probably unloaded.
```

Also half of the time vimeo's default player controls appear in addition of control bar.

### Steps to reproduce

Register vimeo plugin 
Manually call `play()` method

### Expected behavior

Play video

### Screenshots and recordings

![Screenshot 2022-06-22 at 16 30 47](https://user-images.githubusercontent.com/3056832/175055128-863bde0a-2838-42c5-afae-bb64c159cbad.png)
![Screenshot 2022-06-22 at 16 28 30](https://user-images.githubusercontent.com/3056832/175054616-1a3d07fa-52b2-444c-aa53-c861e7e82481.png)

### Vlite.js

4.0.5

### Browser

102.0.5005.115

### OS

macOS 12.4

### Additional context

Used in Vuejs SPA app

**Comment by yoriiis** [comment]
Hello @shamil9,

Thanks for the report.

About this, it is a limitation of Vimeo, not Vlitejs. You need a paid plan to hide control. More information on the [Vimeo embed options documentation](https://github.com/vimeo/player.js/#embed-options) and the [Vimeo plan](https://vimeo.zendesk.com/hc/en-us/articles/228068968-Compare-Vimeo-plans).

> Also half of the time vimeo's default player controls appear in addition of control bar.

**Comment by yoriiis** [comment]
About the error, could you please share a small reproducible repository? On the demo, the Vimeo player works well.

**Comment by shamil9** [comment]
Sure here it is https://github.com/shamil9/vimeo-test

**Comment by yoriiis** [comment]
I think it's related to your implementation with Vue. See this issue:
https://stackoverflow.com/questions/68727191/vimeo-sdk-unknown-player-error-after-initialization-vuejs

Also, I recommand you to manipulate the player only when ready. Use the [onReady](https://github.com/yoriiis/vlitejs#player-ready) callback function (the `player` is automatically exposed as a parameter).

**Comment by shamil9** [comment]
Thanks, indeed looks like Vue problem.
